-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 13:25:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smart_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_db` DEFAULT CHARACTER SET utf8 ;
USE `smart_db` ;

-- -----------------------------------------------------
-- Table `smart_db`.`tabPeople`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_db`.`tabPeople` (
  `idPeople` INT NOT NULL AUTO_INCREMENT,
  `TabNum` VARCHAR(6) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `FatherName` VARCHAR(45) NULL,
  `Driver` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPeople`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX TabNum_idx ON tabPeople (TabNum ASC);

CREATE UNIQUE INDEX idPeople_idx ON tabPeople (idPeople ASC);


-- -----------------------------------------------------
-- Table `smart_db`.`tabPlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_db`.`tabPlace` (
  `idPlace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `FullName` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlace`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPlace_idx` ON `tabPlace` (`idPlace` ASC);


-- -----------------------------------------------------
-- Table `smart_db`.`tabTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_db`.`tabTasks` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `fkPlace` INT NOT NULL,
  `date` DATE NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `content` TEXT NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`idTask`),
  CONSTRAINT `fk_Work_Object1`
    FOREIGN KEY (`fkPlace`)
    REFERENCES `smart_db`.`tabPlace` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Task_Place_idx` ON `tabTasks` (`fkPlace` ASC);

CREATE UNIQUE INDEX `idTask_idx` ON `tabTasks` (`idTask` ASC);


-- -----------------------------------------------------
-- Table `smart_db`.`tabWorker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_db`.`tabWorker` (
  `idWorker` INT NOT NULL AUTO_INCREMENT,
  `fkPeople` INT NOT NULL,
  `fkTask` INT NOT NULL,
  PRIMARY KEY (`idWorker`),
  CONSTRAINT `fk_Workers_People`
    FOREIGN KEY (`fkPeople`)
    REFERENCES `smart_db`.`tabPeople` (`idPeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Workers_Work1`
    FOREIGN KEY (`fkTask`)
    REFERENCES `smart_db`.`tabTasks` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idWorker_idx` ON `tabWorker` (`idWorker` ASC);

CREATE INDEX `fk_Worker_People_idx` ON `tabWorker` (`fkPeople` ASC);

CREATE INDEX `fk_Worker_Task_idx` ON `tabWorker` (`fkTask` ASC);


-- -----------------------------------------------------
-- Table `smart_db`.`tabCar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_db`.`tabCar` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `GosNum` VARCHAR(10) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCar`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCar_UNIQUE` ON `tabCar` (`idCar` ASC);

CREATE UNIQUE INDEX `GNum_UNIQUE` ON `tabCar` (`GosNum` ASC);


-- -----------------------------------------------------
-- Table `smart_db`.`tabTrip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_db`.`tabTrip` (
  `idTrip` INT NOT NULL AUTO_INCREMENT,
  `fkDriver` INT NOT NULL,
  `fkTask` INT NOT NULL,
  `fkCar` INT NOT NULL,
  `PutNum` INT NOT NULL,
  `timeStart` DATETIME NOT NULL,
  `timeFinish` DATETIME NOT NULL,
  PRIMARY KEY (`idTrip`),
  CONSTRAINT `fk_tabDepart_tabCar1`
    FOREIGN KEY (`fkCar`)
    REFERENCES `smart_db`.`tabCar` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabDepart_tabPeople1`
    FOREIGN KEY (`fkDriver`)
    REFERENCES `smart_db`.`tabPeople` (`idPeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabDepart_tabTasks1`
    FOREIGN KEY (`fkTask`)
    REFERENCES `smart_db`.`tabTasks` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idTrip_UNIQUE` ON `tabTrip` (`idTrip` ASC);

CREATE INDEX `fk_Trip_Car_idx` ON `tabTrip` (`fkCar` ASC);

CREATE INDEX `fk_Trip_People_idx` ON `tabTrip` (`fkDriver` ASC);

CREATE INDEX `fk_Trip_Tasks_idx` ON `tabTrip` (`fkTask` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
